// TỰ ĐỘNG SINH RA bởi scripts/tao-template.mjs — không sửa tay.
// Dùng làm dữ liệu chạy thử khi chưa cấu hình Google Sheets.
export default {
  "results": [
    {
      "ma_hoc_sinh": "HS001",
      "ho_ten": "Nguyễn Minh Anh",
      "giao_vien": "Nguyễn Thu Trang",
      "lich_hoc": "18:00 02/03/2026",
      "lop": "D.1C.310000",
      "video_url": "https://example.com/video/buoi-hoc-1",
      "so_cup": "28",
      "gio_tay": "0",
      "tra_loi_dung": "2/10",
      "nhan_xet_tinh_than": "Con học ngoan, tập trung suốt buổi, chủ động giơ tay phát biểu và giữ được năng lượng vui vẻ đến cuối giờ.",
      "hoc_luc": "A - Giỏi",
      "nhan_xet_tong_quan": "Nhìn chung con có nền tảng tốt và khả năng tiếp thu nhanh. Cô định hướng con tập trung cải thiện: (1) Phát âm âm cuối và trọng âm từ; (2) Phản xạ nói cả câu thay vì trả lời bằng từ đơn.",
      "nx_tu_vung": "Con tiếp thu từ vựng rất nhanh, hôm nay con học được 6/6 từ về chủ đề sức khoẻ và ghi nhớ tốt khi được nhắc lại cuối giờ.",
      "nx_ngu_phap": "Con nắm được cấu trúc \"Would you like some...?\" và cách trả lời \"Yes, please / No, thanks\", tuy nhiên chưa chủ động dùng lại khi giao tiếp tự do.",
      "nx_phat_am": "Con nghe và phát âm theo cô tốt. Khi không có mẫu, con còn quên âm cuối ở các từ như \"like\", \"rice\". Cô sẽ củng cố nguyên tắc IPA và chỉnh khẩu hình cho con.",
      "nx_phan_xa": "Con còn rụt rè và có tâm lý sợ sai. Càng về cuối giờ con cởi mở hơn, đã trả lời được cả câu \"I'm happy\" khi cô hỏi.",
      "diem_tu_vung": "8.8",
      "diem_ngu_phap": "9.2",
      "diem_phat_am": "8.6",
      "diem_phan_xa": "9.4",
      "pct_co_ban": "100%",
      "pct_nang_cao": "10%",
      "nhan_xet_lo_trinh": "Dựa trên kết quả buổi học, trung tâm gợi ý con theo lộ trình cá nhân hoá: củng cố nền tảng phát âm trong 4 buổi đầu, sau đó tăng dần tỷ trọng luyện nói.",
      "bac_nang_luc": "Bậc 1-",
      "ngay_cap": "Hà Nội, ngày 1 tháng 3 năm 2026"
    },
    {
      "ma_hoc_sinh": "HS002",
      "ho_ten": "Trần Gia Bảo",
      "giao_vien": "Trần Hoàng Mai",
      "lich_hoc": "19:00 03/03/2026",
      "lop": "D.2C.310137",
      "video_url": "https://example.com/video/buoi-hoc-2",
      "so_cup": "35",
      "gio_tay": "3",
      "tra_loi_dung": "3/10",
      "nhan_xet_tinh_than": "Con có ý thức học tập tốt, tiếp thu từ vựng và cấu trúc mới khá nhanh, tuy nhiên còn hơi rụt rè khi được gọi trả lời.",
      "hoc_luc": "B - Khá",
      "nhan_xet_tong_quan": "Con nắm được kiến thức trong buổi học ở mức khá. Để tiến bộ nhanh hơn, con cần: (1) Luyện nghe chép chính tả 10 phút mỗi ngày; (2) Tăng thời lượng nói để quen phản xạ.",
      "nx_tu_vung": "Con nhớ được khoảng 4/6 từ mới. Với các từ dài, con còn nhầm lẫn thứ tự âm tiết nên cô sẽ chia nhỏ từ theo âm để con dễ ghi nhớ.",
      "nx_ngu_phap": "Con phân biệt được câu khẳng định và câu hỏi, nhưng còn quên chia động từ số ít ngôi thứ ba.",
      "nx_phat_am": "Con phát âm rõ ràng, trọng âm từ khá chuẩn. Cô sẽ nâng dần lên luyện ngữ điệu câu.",
      "nx_phan_xa": "Con phản xạ nhanh với câu hỏi quen thuộc, thời gian nghĩ trung bình dưới 3 giây.",
      "diem_tu_vung": "8.2",
      "diem_ngu_phap": "7.2",
      "diem_phat_am": "8.0",
      "diem_phan_xa": "7.4",
      "pct_co_ban": "100%",
      "pct_nang_cao": "15%",
      "nhan_xet_lo_trinh": "Lộ trình đề xuất cho con: 2 buổi/tuần, ưu tiên mở rộng vốn từ theo chủ đề và luyện phản xạ giao tiếp.",
      "bac_nang_luc": "Bậc 1",
      "ngay_cap": "Hà Nội, ngày 2 tháng 3 năm 2026"
    },
    {
      "ma_hoc_sinh": "HS003",
      "ho_ten": "Lê Khánh Chi",
      "giao_vien": "Lê Ngọc Ánh",
      "lich_hoc": "17:30 04/03/2026",
      "lop": "D.3C.310274",
      "video_url": "https://example.com/video/buoi-hoc-3",
      "so_cup": "42",
      "gio_tay": "6",
      "tra_loi_dung": "4/10",
      "nhan_xet_tinh_than": "Con hợp tác tốt với cô, làm theo hướng dẫn đầy đủ. Nửa sau buổi học con có dấu hiệu mất tập trung nhẹ, cô đã dùng trò chơi để kéo con trở lại bài.",
      "hoc_luc": "C - Trung Bình",
      "nhan_xet_tong_quan": "Con có ý thức học tập nhưng nền từ vựng còn mỏng. Cô sẽ ưu tiên: (1) Củng cố bộ từ vựng nền theo chủ đề; (2) Hướng dẫn lại nguyên tắc phát âm chuẩn IPA để con đọc đúng ngay từ đầu.",
      "nx_tu_vung": "Con nắm nghĩa từ vựng tốt qua hình ảnh nhưng chưa vận dụng được vào câu. Cô sẽ tạo thêm nhiều ngữ cảnh để con dùng lại từ đã học.",
      "nx_ngu_phap": "Con áp dụng đúng cấu trúc trong bài tập có sẵn khung. Khi phải tự đặt câu, con còn cần cô gợi ý từ đầu tiên.",
      "nx_phat_am": "Khẩu hình của con với một số nguyên âm đôi chưa chính xác. Cô sẽ dùng gương và video đối chiếu để con tự chỉnh.",
      "nx_phan_xa": "Con thường trả lời bằng từ đơn. Cô sẽ khuyến khích con mở rộng thành câu đầy đủ bằng cách hỏi thêm \"Why?\" sau mỗi câu trả lời.",
      "diem_tu_vung": "5.8",
      "diem_ngu_phap": "6.2",
      "diem_phat_am": "5.6",
      "diem_phan_xa": "6.4",
      "pct_co_ban": "100%",
      "pct_nang_cao": "20%",
      "nhan_xet_lo_trinh": "Con phù hợp với lộ trình tăng tốc: học song song kiến thức cơ bản và mở rộng chủ đề nâng cao để chuẩn bị cho các kỳ thi trong năm học.",
      "bac_nang_luc": "Bậc 2",
      "ngay_cap": "Hà Nội, ngày 3 tháng 3 năm 2026"
    },
    {
      "ma_hoc_sinh": "HS004",
      "ho_ten": "Phạm Đức Duy",
      "giao_vien": "Phạm Hải Yến",
      "lich_hoc": "20:00 05/03/2026",
      "lop": "D.4C.310411",
      "video_url": "https://example.com/video/buoi-hoc-4",
      "so_cup": "49",
      "gio_tay": "0",
      "tra_loi_dung": "5/10",
      "nhan_xet_tinh_than": "Con rất hào hứng với các hoạt động tương tác, chủ động đặt câu hỏi khi chưa hiểu — đây là điểm mạnh cần duy trì.",
      "hoc_luc": "B - Khá",
      "nhan_xet_tong_quan": "Con thể hiện tốt ở kỹ năng nghe và đọc, nhưng nói còn thiếu tự tin. Lộ trình tiếp theo sẽ tăng tỷ trọng hoạt động giao tiếp cặp đôi để con mạnh dạn hơn.",
      "nx_tu_vung": "Vốn từ của con khá phong phú so với bạn cùng lứa, con còn chủ động dùng từ đã học ở buổi trước vào bài hôm nay.",
      "nx_ngu_phap": "Con sử dụng thành thạo thì hiện tại đơn và bắt đầu dùng đúng thì hiện tại tiếp diễn trong ngữ cảnh phù hợp.",
      "nx_phat_am": "Con còn ảnh hưởng cách đọc tiếng Việt khi phát âm phụ âm đầu. Cô ưu tiên sửa nhóm âm /θ/, /ð/ và /s/ - /ʃ/ trong các buổi tới.",
      "nx_phan_xa": "Con chủ động hỏi lại cô khi chưa nghe rõ — đây là thói quen rất tốt cần duy trì.",
      "diem_tu_vung": "8.0",
      "diem_ngu_phap": "8.4",
      "diem_phat_am": "7.8",
      "diem_phan_xa": "7.2",
      "pct_co_ban": "100%",
      "pct_nang_cao": "25%",
      "nhan_xet_lo_trinh": "Trung tâm đề xuất con học nhóm nhỏ 1 kèm 3 để vừa có bạn tương tác, vừa được cô theo sát khi phát âm.",
      "bac_nang_luc": "Bậc 1",
      "ngay_cap": "Hà Nội, ngày 4 tháng 3 năm 2026"
    },
    {
      "ma_hoc_sinh": "HS005",
      "ho_ten": "Hoàng Thuỳ Dương",
      "giao_vien": "Đỗ Thanh Huyền",
      "lich_hoc": "18:30 06/03/2026",
      "lop": "D.5C.310548",
      "video_url": "https://example.com/video/buoi-hoc-5",
      "so_cup": "56",
      "gio_tay": "3",
      "tra_loi_dung": "6/10",
      "nhan_xet_tinh_than": "Con ngồi học nghiêm túc nhưng còn ít phát biểu. Cô sẽ tăng các câu hỏi mở để con tự tin hơn trong các buổi tới.",
      "hoc_luc": "A - Giỏi",
      "nhan_xet_tong_quan": "Con tiếp thu nhanh nhưng còn thiếu tính chính xác về ngữ pháp. Cô sẽ bổ sung bài tập vận dụng có kiểm soát trước khi cho con nói tự do.",
      "nx_tu_vung": "Con cần thêm thời gian ôn từ vựng ở nhà. Cô đề xuất phụ huynh cho con ôn 5-7 phút mỗi tối bằng flashcard.",
      "nx_ngu_phap": "Cô sẽ củng cố lại trật tự từ trong câu hỏi Wh- vì con còn đảo sai vị trí trợ động từ.",
      "nx_phat_am": "Con bắt chước ngữ điệu của cô rất tốt, nói câu nghe tự nhiên và có nhịp.",
      "nx_phan_xa": "Con cần tăng môi trường giao tiếp để bớt phụ thuộc vào việc dịch sang tiếng Việt trong đầu trước khi nói.",
      "diem_tu_vung": "8.4",
      "diem_ngu_phap": "8.8",
      "diem_phat_am": "9.6",
      "diem_phan_xa": "9.0",
      "pct_co_ban": "100%",
      "pct_nang_cao": "10%",
      "nhan_xet_lo_trinh": "Dựa trên kết quả buổi học, trung tâm gợi ý con theo lộ trình cá nhân hoá: củng cố nền tảng phát âm trong 4 buổi đầu, sau đó tăng dần tỷ trọng luyện nói.",
      "bac_nang_luc": "Bậc 3",
      "ngay_cap": "Hà Nội, ngày 5 tháng 3 năm 2026"
    },
    {
      "ma_hoc_sinh": "HS006",
      "ho_ten": "Vũ Nhật Hạ",
      "giao_vien": "Hoàng Minh Châu",
      "lich_hoc": "09:00 07/03/2026",
      "lop": "D.1C.310685",
      "video_url": "https://example.com/video/buoi-hoc-6",
      "so_cup": "63",
      "gio_tay": "6",
      "tra_loi_dung": "7/10",
      "nhan_xet_tinh_than": "Con tiếp thu bài ổn, ghi chép đầy đủ và hoàn thành hết các bài tập trong buổi.",
      "hoc_luc": "C - Trung Bình",
      "nhan_xet_tong_quan": "Con cần thêm thời gian để làm quen với môi trường học tiếng Anh. Cô định hướng đi chậm và chắc: học kỹ từng nhóm từ vựng, kết hợp trò chơi để con thấy hứng thú.",
      "nx_tu_vung": "Con nhận diện mặt chữ tốt, đọc lại được hầu hết từ mới sau 2 lần nghe mẫu.",
      "nx_ngu_phap": "Con hiểu quy tắc nhưng tốc độ vận dụng còn chậm. Cô sẽ tăng bài tập phản xạ nhanh để rút ngắn thời gian con nghĩ câu trả lời.",
      "nx_phat_am": "Phát âm của con ở mức ổn. Cần chú ý nối âm khi nói cả câu để nghe trôi chảy hơn.",
      "nx_phan_xa": "Con tự tin tương tác, dám nói dù chưa chắc đúng. Cô đánh giá cao tinh thần này.",
      "diem_tu_vung": "6.2",
      "diem_ngu_phap": "6.6",
      "diem_phat_am": "6.0",
      "diem_phan_xa": "6.8",
      "pct_co_ban": "100%",
      "pct_nang_cao": "15%",
      "nhan_xet_lo_trinh": "Lộ trình đề xuất cho con: 2 buổi/tuần, ưu tiên mở rộng vốn từ theo chủ đề và luyện phản xạ giao tiếp.",
      "bac_nang_luc": "Bậc 1-",
      "ngay_cap": "Hà Nội, ngày 6 tháng 3 năm 2026"
    },
    {
      "ma_hoc_sinh": "HS007",
      "ho_ten": "Đặng Quang Huy",
      "giao_vien": "Nguyễn Thu Trang",
      "lich_hoc": "10:30 08/03/2026",
      "lop": "D.2C.310822",
      "video_url": "https://example.com/video/buoi-hoc-7",
      "so_cup": "70",
      "gio_tay": "0",
      "tra_loi_dung": "8/10",
      "nhan_xet_tinh_than": "Con học ngoan, tập trung suốt buổi, chủ động giơ tay phát biểu và giữ được năng lượng vui vẻ đến cuối giờ.",
      "hoc_luc": "D - Cần cố gắng",
      "nhan_xet_tong_quan": "Nhìn chung con có nền tảng tốt và khả năng tiếp thu nhanh. Cô định hướng con tập trung cải thiện: (1) Phát âm âm cuối và trọng âm từ; (2) Phản xạ nói cả câu thay vì trả lời bằng từ đơn.",
      "nx_tu_vung": "Con tiếp thu từ vựng rất nhanh, hôm nay con học được 6/6 từ về chủ đề sức khoẻ và ghi nhớ tốt khi được nhắc lại cuối giờ.",
      "nx_ngu_phap": "Con nắm được cấu trúc \"Would you like some...?\" và cách trả lời \"Yes, please / No, thanks\", tuy nhiên chưa chủ động dùng lại khi giao tiếp tự do.",
      "nx_phat_am": "Con nghe và phát âm theo cô tốt. Khi không có mẫu, con còn quên âm cuối ở các từ như \"like\", \"rice\". Cô sẽ củng cố nguyên tắc IPA và chỉnh khẩu hình cho con.",
      "nx_phan_xa": "Con còn rụt rè và có tâm lý sợ sai. Càng về cuối giờ con cởi mở hơn, đã trả lời được cả câu \"I'm happy\" khi cô hỏi.",
      "diem_tu_vung": "5.4",
      "diem_ngu_phap": "4.4",
      "diem_phat_am": "5.2",
      "diem_phan_xa": "4.6",
      "pct_co_ban": "100%",
      "pct_nang_cao": "20%",
      "nhan_xet_lo_trinh": "Con phù hợp với lộ trình tăng tốc: học song song kiến thức cơ bản và mở rộng chủ đề nâng cao để chuẩn bị cho các kỳ thi trong năm học.",
      "bac_nang_luc": "Bậc 2",
      "ngay_cap": "Hà Nội, ngày 7 tháng 3 năm 2026"
    },
    {
      "ma_hoc_sinh": "HS008",
      "ho_ten": "Bùi Thảo Linh",
      "giao_vien": "Trần Hoàng Mai",
      "lich_hoc": "18:00 02/03/2026",
      "lop": "D.3C.310959",
      "video_url": "https://example.com/video/buoi-hoc-8",
      "so_cup": "32",
      "gio_tay": "3",
      "tra_loi_dung": "9/10",
      "nhan_xet_tinh_than": "Con có ý thức học tập tốt, tiếp thu từ vựng và cấu trúc mới khá nhanh, tuy nhiên còn hơi rụt rè khi được gọi trả lời.",
      "hoc_luc": "A - Giỏi",
      "nhan_xet_tong_quan": "Con nắm được kiến thức trong buổi học ở mức khá. Để tiến bộ nhanh hơn, con cần: (1) Luyện nghe chép chính tả 10 phút mỗi ngày; (2) Tăng thời lượng nói để quen phản xạ.",
      "nx_tu_vung": "Con nhớ được khoảng 4/6 từ mới. Với các từ dài, con còn nhầm lẫn thứ tự âm tiết nên cô sẽ chia nhỏ từ theo âm để con dễ ghi nhớ.",
      "nx_ngu_phap": "Con phân biệt được câu khẳng định và câu hỏi, nhưng còn quên chia động từ số ít ngôi thứ ba.",
      "nx_phat_am": "Con phát âm rõ ràng, trọng âm từ khá chuẩn. Cô sẽ nâng dần lên luyện ngữ điệu câu.",
      "nx_phan_xa": "Con phản xạ nhanh với câu hỏi quen thuộc, thời gian nghĩ trung bình dưới 3 giây.",
      "diem_tu_vung": "8.8",
      "diem_ngu_phap": "9.2",
      "diem_phat_am": "8.6",
      "diem_phan_xa": "9.4",
      "pct_co_ban": "100%",
      "pct_nang_cao": "25%",
      "nhan_xet_lo_trinh": "Trung tâm đề xuất con học nhóm nhỏ 1 kèm 3 để vừa có bạn tương tác, vừa được cô theo sát khi phát âm.",
      "bac_nang_luc": "Bậc 1-",
      "ngay_cap": "Hà Nội, ngày 8 tháng 3 năm 2026"
    },
    {
      "ma_hoc_sinh": "HS009",
      "ho_ten": "Đỗ Bảo Long",
      "giao_vien": "Lê Ngọc Ánh",
      "lich_hoc": "19:00 03/03/2026",
      "lop": "D.4C.311096",
      "video_url": "https://example.com/video/buoi-hoc-9",
      "so_cup": "39",
      "gio_tay": "6",
      "tra_loi_dung": "2/10",
      "nhan_xet_tinh_than": "Con hợp tác tốt với cô, làm theo hướng dẫn đầy đủ. Nửa sau buổi học con có dấu hiệu mất tập trung nhẹ, cô đã dùng trò chơi để kéo con trở lại bài.",
      "hoc_luc": "B - Khá",
      "nhan_xet_tong_quan": "Con có ý thức học tập nhưng nền từ vựng còn mỏng. Cô sẽ ưu tiên: (1) Củng cố bộ từ vựng nền theo chủ đề; (2) Hướng dẫn lại nguyên tắc phát âm chuẩn IPA để con đọc đúng ngay từ đầu.",
      "nx_tu_vung": "Con nắm nghĩa từ vựng tốt qua hình ảnh nhưng chưa vận dụng được vào câu. Cô sẽ tạo thêm nhiều ngữ cảnh để con dùng lại từ đã học.",
      "nx_ngu_phap": "Con áp dụng đúng cấu trúc trong bài tập có sẵn khung. Khi phải tự đặt câu, con còn cần cô gợi ý từ đầu tiên.",
      "nx_phat_am": "Khẩu hình của con với một số nguyên âm đôi chưa chính xác. Cô sẽ dùng gương và video đối chiếu để con tự chỉnh.",
      "nx_phan_xa": "Con thường trả lời bằng từ đơn. Cô sẽ khuyến khích con mở rộng thành câu đầy đủ bằng cách hỏi thêm \"Why?\" sau mỗi câu trả lời.",
      "diem_tu_vung": "8.2",
      "diem_ngu_phap": "7.2",
      "diem_phat_am": "8.0",
      "diem_phan_xa": "7.4",
      "pct_co_ban": "100%",
      "pct_nang_cao": "10%",
      "nhan_xet_lo_trinh": "Dựa trên kết quả buổi học, trung tâm gợi ý con theo lộ trình cá nhân hoá: củng cố nền tảng phát âm trong 4 buổi đầu, sau đó tăng dần tỷ trọng luyện nói.",
      "bac_nang_luc": "Bậc 1",
      "ngay_cap": "Hà Nội, ngày 9 tháng 3 năm 2026"
    },
    {
      "ma_hoc_sinh": "HS010",
      "ho_ten": "Ngô Phương Mai",
      "giao_vien": "Phạm Hải Yến",
      "lich_hoc": "17:30 04/03/2026",
      "lop": "D.5C.311233",
      "video_url": "https://example.com/video/buoi-hoc-10",
      "so_cup": "46",
      "gio_tay": "0",
      "tra_loi_dung": "3/10",
      "nhan_xet_tinh_than": "Con rất hào hứng với các hoạt động tương tác, chủ động đặt câu hỏi khi chưa hiểu — đây là điểm mạnh cần duy trì.",
      "hoc_luc": "C - Trung Bình",
      "nhan_xet_tong_quan": "Con thể hiện tốt ở kỹ năng nghe và đọc, nhưng nói còn thiếu tự tin. Lộ trình tiếp theo sẽ tăng tỷ trọng hoạt động giao tiếp cặp đôi để con mạnh dạn hơn.",
      "nx_tu_vung": "Vốn từ của con khá phong phú so với bạn cùng lứa, con còn chủ động dùng từ đã học ở buổi trước vào bài hôm nay.",
      "nx_ngu_phap": "Con sử dụng thành thạo thì hiện tại đơn và bắt đầu dùng đúng thì hiện tại tiếp diễn trong ngữ cảnh phù hợp.",
      "nx_phat_am": "Con còn ảnh hưởng cách đọc tiếng Việt khi phát âm phụ âm đầu. Cô ưu tiên sửa nhóm âm /θ/, /ð/ và /s/ - /ʃ/ trong các buổi tới.",
      "nx_phan_xa": "Con chủ động hỏi lại cô khi chưa nghe rõ — đây là thói quen rất tốt cần duy trì.",
      "diem_tu_vung": "5.8",
      "diem_ngu_phap": "6.2",
      "diem_phat_am": "5.6",
      "diem_phan_xa": "6.4",
      "pct_co_ban": "100%",
      "pct_nang_cao": "15%",
      "nhan_xet_lo_trinh": "Lộ trình đề xuất cho con: 2 buổi/tuần, ưu tiên mở rộng vốn từ theo chủ đề và luyện phản xạ giao tiếp.",
      "bac_nang_luc": "Bậc 2",
      "ngay_cap": "Hà Nội, ngày 10 tháng 3 năm 2026"
    },
    {
      "ma_hoc_sinh": "HS011",
      "ho_ten": "Dương Tuấn Kiệt",
      "giao_vien": "Đỗ Thanh Huyền",
      "lich_hoc": "20:00 05/03/2026",
      "lop": "D.1C.311370",
      "video_url": "https://example.com/video/buoi-hoc-11",
      "so_cup": "53",
      "gio_tay": "3",
      "tra_loi_dung": "4/10",
      "nhan_xet_tinh_than": "Con ngồi học nghiêm túc nhưng còn ít phát biểu. Cô sẽ tăng các câu hỏi mở để con tự tin hơn trong các buổi tới.",
      "hoc_luc": "B - Khá",
      "nhan_xet_tong_quan": "Con tiếp thu nhanh nhưng còn thiếu tính chính xác về ngữ pháp. Cô sẽ bổ sung bài tập vận dụng có kiểm soát trước khi cho con nói tự do.",
      "nx_tu_vung": "Con cần thêm thời gian ôn từ vựng ở nhà. Cô đề xuất phụ huynh cho con ôn 5-7 phút mỗi tối bằng flashcard.",
      "nx_ngu_phap": "Cô sẽ củng cố lại trật tự từ trong câu hỏi Wh- vì con còn đảo sai vị trí trợ động từ.",
      "nx_phat_am": "Con bắt chước ngữ điệu của cô rất tốt, nói câu nghe tự nhiên và có nhịp.",
      "nx_phan_xa": "Con cần tăng môi trường giao tiếp để bớt phụ thuộc vào việc dịch sang tiếng Việt trong đầu trước khi nói.",
      "diem_tu_vung": "8.0",
      "diem_ngu_phap": "8.4",
      "diem_phat_am": "7.8",
      "diem_phan_xa": "7.2",
      "pct_co_ban": "100%",
      "pct_nang_cao": "20%",
      "nhan_xet_lo_trinh": "Con phù hợp với lộ trình tăng tốc: học song song kiến thức cơ bản và mở rộng chủ đề nâng cao để chuẩn bị cho các kỳ thi trong năm học.",
      "bac_nang_luc": "Bậc 1",
      "ngay_cap": "Hà Nội, ngày 11 tháng 3 năm 2026"
    },
    {
      "ma_hoc_sinh": "HS012",
      "ho_ten": "Lý Ngọc Diệp",
      "giao_vien": "Hoàng Minh Châu",
      "lich_hoc": "18:30 06/03/2026",
      "lop": "D.2C.311507",
      "video_url": "https://example.com/video/buoi-hoc-12",
      "so_cup": "60",
      "gio_tay": "6",
      "tra_loi_dung": "5/10",
      "nhan_xet_tinh_than": "Con tiếp thu bài ổn, ghi chép đầy đủ và hoàn thành hết các bài tập trong buổi.",
      "hoc_luc": "A - Giỏi",
      "nhan_xet_tong_quan": "Con cần thêm thời gian để làm quen với môi trường học tiếng Anh. Cô định hướng đi chậm và chắc: học kỹ từng nhóm từ vựng, kết hợp trò chơi để con thấy hứng thú.",
      "nx_tu_vung": "Con nhận diện mặt chữ tốt, đọc lại được hầu hết từ mới sau 2 lần nghe mẫu.",
      "nx_ngu_phap": "Con hiểu quy tắc nhưng tốc độ vận dụng còn chậm. Cô sẽ tăng bài tập phản xạ nhanh để rút ngắn thời gian con nghĩ câu trả lời.",
      "nx_phat_am": "Phát âm của con ở mức ổn. Cần chú ý nối âm khi nói cả câu để nghe trôi chảy hơn.",
      "nx_phan_xa": "Con tự tin tương tác, dám nói dù chưa chắc đúng. Cô đánh giá cao tinh thần này.",
      "diem_tu_vung": "8.4",
      "diem_ngu_phap": "8.8",
      "diem_phat_am": "9.6",
      "diem_phan_xa": "9.0",
      "pct_co_ban": "100%",
      "pct_nang_cao": "25%",
      "nhan_xet_lo_trinh": "Trung tâm đề xuất con học nhóm nhỏ 1 kèm 3 để vừa có bạn tương tác, vừa được cô theo sát khi phát âm.",
      "bac_nang_luc": "Bậc 3",
      "ngay_cap": "Hà Nội, ngày 12 tháng 3 năm 2026"
    },
    {
      "ma_hoc_sinh": "HS013",
      "ho_ten": "Trịnh Hoàng Nam",
      "giao_vien": "Nguyễn Thu Trang",
      "lich_hoc": "09:00 07/03/2026",
      "lop": "D.3C.311644",
      "video_url": "https://example.com/video/buoi-hoc-13",
      "so_cup": "67",
      "gio_tay": "0",
      "tra_loi_dung": "6/10",
      "nhan_xet_tinh_than": "Con học ngoan, tập trung suốt buổi, chủ động giơ tay phát biểu và giữ được năng lượng vui vẻ đến cuối giờ.",
      "hoc_luc": "C - Trung Bình",
      "nhan_xet_tong_quan": "Nhìn chung con có nền tảng tốt và khả năng tiếp thu nhanh. Cô định hướng con tập trung cải thiện: (1) Phát âm âm cuối và trọng âm từ; (2) Phản xạ nói cả câu thay vì trả lời bằng từ đơn.",
      "nx_tu_vung": "Con tiếp thu từ vựng rất nhanh, hôm nay con học được 6/6 từ về chủ đề sức khoẻ và ghi nhớ tốt khi được nhắc lại cuối giờ.",
      "nx_ngu_phap": "Con nắm được cấu trúc \"Would you like some...?\" và cách trả lời \"Yes, please / No, thanks\", tuy nhiên chưa chủ động dùng lại khi giao tiếp tự do.",
      "nx_phat_am": "Con nghe và phát âm theo cô tốt. Khi không có mẫu, con còn quên âm cuối ở các từ như \"like\", \"rice\". Cô sẽ củng cố nguyên tắc IPA và chỉnh khẩu hình cho con.",
      "nx_phan_xa": "Con còn rụt rè và có tâm lý sợ sai. Càng về cuối giờ con cởi mở hơn, đã trả lời được cả câu \"I'm happy\" khi cô hỏi.",
      "diem_tu_vung": "6.2",
      "diem_ngu_phap": "6.6",
      "diem_phat_am": "6.0",
      "diem_phan_xa": "6.8",
      "pct_co_ban": "100%",
      "pct_nang_cao": "10%",
      "nhan_xet_lo_trinh": "Dựa trên kết quả buổi học, trung tâm gợi ý con theo lộ trình cá nhân hoá: củng cố nền tảng phát âm trong 4 buổi đầu, sau đó tăng dần tỷ trọng luyện nói.",
      "bac_nang_luc": "Bậc 1-",
      "ngay_cap": "Hà Nội, ngày 13 tháng 3 năm 2026"
    },
    {
      "ma_hoc_sinh": "HS014",
      "ho_ten": "Cao Bảo Ngân",
      "giao_vien": "Trần Hoàng Mai",
      "lich_hoc": "10:30 08/03/2026",
      "lop": "D.4C.311781",
      "video_url": "https://example.com/video/buoi-hoc-14",
      "so_cup": "29",
      "gio_tay": "3",
      "tra_loi_dung": "7/10",
      "nhan_xet_tinh_than": "Con có ý thức học tập tốt, tiếp thu từ vựng và cấu trúc mới khá nhanh, tuy nhiên còn hơi rụt rè khi được gọi trả lời.",
      "hoc_luc": "D - Cần cố gắng",
      "nhan_xet_tong_quan": "Con nắm được kiến thức trong buổi học ở mức khá. Để tiến bộ nhanh hơn, con cần: (1) Luyện nghe chép chính tả 10 phút mỗi ngày; (2) Tăng thời lượng nói để quen phản xạ.",
      "nx_tu_vung": "Con nhớ được khoảng 4/6 từ mới. Với các từ dài, con còn nhầm lẫn thứ tự âm tiết nên cô sẽ chia nhỏ từ theo âm để con dễ ghi nhớ.",
      "nx_ngu_phap": "Con phân biệt được câu khẳng định và câu hỏi, nhưng còn quên chia động từ số ít ngôi thứ ba.",
      "nx_phat_am": "Con phát âm rõ ràng, trọng âm từ khá chuẩn. Cô sẽ nâng dần lên luyện ngữ điệu câu.",
      "nx_phan_xa": "Con phản xạ nhanh với câu hỏi quen thuộc, thời gian nghĩ trung bình dưới 3 giây.",
      "diem_tu_vung": "5.4",
      "diem_ngu_phap": "4.4",
      "diem_phat_am": "5.2",
      "diem_phan_xa": "4.6",
      "pct_co_ban": "100%",
      "pct_nang_cao": "15%",
      "nhan_xet_lo_trinh": "Lộ trình đề xuất cho con: 2 buổi/tuần, ưu tiên mở rộng vốn từ theo chủ đề và luyện phản xạ giao tiếp.",
      "bac_nang_luc": "Bậc 2",
      "ngay_cap": "Hà Nội, ngày 14 tháng 3 năm 2026"
    },
    {
      "ma_hoc_sinh": "HS015",
      "ho_ten": "Đinh Gia Hân",
      "giao_vien": "Lê Ngọc Ánh",
      "lich_hoc": "18:00 02/03/2026",
      "lop": "D.5C.311918",
      "video_url": "https://example.com/video/buoi-hoc-15",
      "so_cup": "36",
      "gio_tay": "6",
      "tra_loi_dung": "8/10",
      "nhan_xet_tinh_than": "Con hợp tác tốt với cô, làm theo hướng dẫn đầy đủ. Nửa sau buổi học con có dấu hiệu mất tập trung nhẹ, cô đã dùng trò chơi để kéo con trở lại bài.",
      "hoc_luc": "A - Giỏi",
      "nhan_xet_tong_quan": "Con có ý thức học tập nhưng nền từ vựng còn mỏng. Cô sẽ ưu tiên: (1) Củng cố bộ từ vựng nền theo chủ đề; (2) Hướng dẫn lại nguyên tắc phát âm chuẩn IPA để con đọc đúng ngay từ đầu.",
      "nx_tu_vung": "Con nắm nghĩa từ vựng tốt qua hình ảnh nhưng chưa vận dụng được vào câu. Cô sẽ tạo thêm nhiều ngữ cảnh để con dùng lại từ đã học.",
      "nx_ngu_phap": "Con áp dụng đúng cấu trúc trong bài tập có sẵn khung. Khi phải tự đặt câu, con còn cần cô gợi ý từ đầu tiên.",
      "nx_phat_am": "Khẩu hình của con với một số nguyên âm đôi chưa chính xác. Cô sẽ dùng gương và video đối chiếu để con tự chỉnh.",
      "nx_phan_xa": "Con thường trả lời bằng từ đơn. Cô sẽ khuyến khích con mở rộng thành câu đầy đủ bằng cách hỏi thêm \"Why?\" sau mỗi câu trả lời.",
      "diem_tu_vung": "8.8",
      "diem_ngu_phap": "9.2",
      "diem_phat_am": "8.6",
      "diem_phan_xa": "9.4",
      "pct_co_ban": "100%",
      "pct_nang_cao": "20%",
      "nhan_xet_lo_trinh": "Con phù hợp với lộ trình tăng tốc: học song song kiến thức cơ bản và mở rộng chủ đề nâng cao để chuẩn bị cho các kỳ thi trong năm học.",
      "bac_nang_luc": "Bậc 1-",
      "ngay_cap": "Hà Nội, ngày 15 tháng 3 năm 2026"
    },
    {
      "ma_hoc_sinh": "HS016",
      "ho_ten": "Phan Minh Khôi",
      "giao_vien": "Phạm Hải Yến",
      "lich_hoc": "19:00 03/03/2026",
      "lop": "D.1C.312055",
      "video_url": "https://example.com/video/buoi-hoc-16",
      "so_cup": "43",
      "gio_tay": "0",
      "tra_loi_dung": "9/10",
      "nhan_xet_tinh_than": "Con rất hào hứng với các hoạt động tương tác, chủ động đặt câu hỏi khi chưa hiểu — đây là điểm mạnh cần duy trì.",
      "hoc_luc": "B - Khá",
      "nhan_xet_tong_quan": "Con thể hiện tốt ở kỹ năng nghe và đọc, nhưng nói còn thiếu tự tin. Lộ trình tiếp theo sẽ tăng tỷ trọng hoạt động giao tiếp cặp đôi để con mạnh dạn hơn.",
      "nx_tu_vung": "Vốn từ của con khá phong phú so với bạn cùng lứa, con còn chủ động dùng từ đã học ở buổi trước vào bài hôm nay.",
      "nx_ngu_phap": "Con sử dụng thành thạo thì hiện tại đơn và bắt đầu dùng đúng thì hiện tại tiếp diễn trong ngữ cảnh phù hợp.",
      "nx_phat_am": "Con còn ảnh hưởng cách đọc tiếng Việt khi phát âm phụ âm đầu. Cô ưu tiên sửa nhóm âm /θ/, /ð/ và /s/ - /ʃ/ trong các buổi tới.",
      "nx_phan_xa": "Con chủ động hỏi lại cô khi chưa nghe rõ — đây là thói quen rất tốt cần duy trì.",
      "diem_tu_vung": "8.2",
      "diem_ngu_phap": "7.2",
      "diem_phat_am": "8.0",
      "diem_phan_xa": "7.4",
      "pct_co_ban": "100%",
      "pct_nang_cao": "25%",
      "nhan_xet_lo_trinh": "Trung tâm đề xuất con học nhóm nhỏ 1 kèm 3 để vừa có bạn tương tác, vừa được cô theo sát khi phát âm.",
      "bac_nang_luc": "Bậc 1",
      "ngay_cap": "Hà Nội, ngày 16 tháng 3 năm 2026"
    },
    {
      "ma_hoc_sinh": "HS017",
      "ho_ten": "Võ Hà My",
      "giao_vien": "Đỗ Thanh Huyền",
      "lich_hoc": "17:30 04/03/2026",
      "lop": "D.2C.312192",
      "video_url": "https://example.com/video/buoi-hoc-17",
      "so_cup": "50",
      "gio_tay": "3",
      "tra_loi_dung": "2/10",
      "nhan_xet_tinh_than": "Con ngồi học nghiêm túc nhưng còn ít phát biểu. Cô sẽ tăng các câu hỏi mở để con tự tin hơn trong các buổi tới.",
      "hoc_luc": "C - Trung Bình",
      "nhan_xet_tong_quan": "Con tiếp thu nhanh nhưng còn thiếu tính chính xác về ngữ pháp. Cô sẽ bổ sung bài tập vận dụng có kiểm soát trước khi cho con nói tự do.",
      "nx_tu_vung": "Con cần thêm thời gian ôn từ vựng ở nhà. Cô đề xuất phụ huynh cho con ôn 5-7 phút mỗi tối bằng flashcard.",
      "nx_ngu_phap": "Cô sẽ củng cố lại trật tự từ trong câu hỏi Wh- vì con còn đảo sai vị trí trợ động từ.",
      "nx_phat_am": "Con bắt chước ngữ điệu của cô rất tốt, nói câu nghe tự nhiên và có nhịp.",
      "nx_phan_xa": "Con cần tăng môi trường giao tiếp để bớt phụ thuộc vào việc dịch sang tiếng Việt trong đầu trước khi nói.",
      "diem_tu_vung": "5.8",
      "diem_ngu_phap": "6.2",
      "diem_phat_am": "5.6",
      "diem_phan_xa": "6.4",
      "pct_co_ban": "100%",
      "pct_nang_cao": "10%",
      "nhan_xet_lo_trinh": "Dựa trên kết quả buổi học, trung tâm gợi ý con theo lộ trình cá nhân hoá: củng cố nền tảng phát âm trong 4 buổi đầu, sau đó tăng dần tỷ trọng luyện nói.",
      "bac_nang_luc": "Bậc 2",
      "ngay_cap": "Hà Nội, ngày 17 tháng 3 năm 2026"
    },
    {
      "ma_hoc_sinh": "HS018",
      "ho_ten": "Tạ Đăng Khoa",
      "giao_vien": "Hoàng Minh Châu",
      "lich_hoc": "20:00 05/03/2026",
      "lop": "D.3C.312329",
      "video_url": "https://example.com/video/buoi-hoc-18",
      "so_cup": "57",
      "gio_tay": "6",
      "tra_loi_dung": "3/10",
      "nhan_xet_tinh_than": "Con tiếp thu bài ổn, ghi chép đầy đủ và hoàn thành hết các bài tập trong buổi.",
      "hoc_luc": "B - Khá",
      "nhan_xet_tong_quan": "Con cần thêm thời gian để làm quen với môi trường học tiếng Anh. Cô định hướng đi chậm và chắc: học kỹ từng nhóm từ vựng, kết hợp trò chơi để con thấy hứng thú.",
      "nx_tu_vung": "Con nhận diện mặt chữ tốt, đọc lại được hầu hết từ mới sau 2 lần nghe mẫu.",
      "nx_ngu_phap": "Con hiểu quy tắc nhưng tốc độ vận dụng còn chậm. Cô sẽ tăng bài tập phản xạ nhanh để rút ngắn thời gian con nghĩ câu trả lời.",
      "nx_phat_am": "Phát âm của con ở mức ổn. Cần chú ý nối âm khi nói cả câu để nghe trôi chảy hơn.",
      "nx_phan_xa": "Con tự tin tương tác, dám nói dù chưa chắc đúng. Cô đánh giá cao tinh thần này.",
      "diem_tu_vung": "8.0",
      "diem_ngu_phap": "8.4",
      "diem_phat_am": "7.8",
      "diem_phan_xa": "7.2",
      "pct_co_ban": "100%",
      "pct_nang_cao": "15%",
      "nhan_xet_lo_trinh": "Lộ trình đề xuất cho con: 2 buổi/tuần, ưu tiên mở rộng vốn từ theo chủ đề và luyện phản xạ giao tiếp.",
      "bac_nang_luc": "Bậc 1",
      "ngay_cap": "Hà Nội, ngày 18 tháng 3 năm 2026"
    },
    {
      "ma_hoc_sinh": "HS019",
      "ho_ten": "Lương Thanh Trúc",
      "giao_vien": "Nguyễn Thu Trang",
      "lich_hoc": "18:30 06/03/2026",
      "lop": "D.4C.312466",
      "video_url": "https://example.com/video/buoi-hoc-19",
      "so_cup": "64",
      "gio_tay": "0",
      "tra_loi_dung": "4/10",
      "nhan_xet_tinh_than": "Con học ngoan, tập trung suốt buổi, chủ động giơ tay phát biểu và giữ được năng lượng vui vẻ đến cuối giờ.",
      "hoc_luc": "A - Giỏi",
      "nhan_xet_tong_quan": "Nhìn chung con có nền tảng tốt và khả năng tiếp thu nhanh. Cô định hướng con tập trung cải thiện: (1) Phát âm âm cuối và trọng âm từ; (2) Phản xạ nói cả câu thay vì trả lời bằng từ đơn.",
      "nx_tu_vung": "Con tiếp thu từ vựng rất nhanh, hôm nay con học được 6/6 từ về chủ đề sức khoẻ và ghi nhớ tốt khi được nhắc lại cuối giờ.",
      "nx_ngu_phap": "Con nắm được cấu trúc \"Would you like some...?\" và cách trả lời \"Yes, please / No, thanks\", tuy nhiên chưa chủ động dùng lại khi giao tiếp tự do.",
      "nx_phat_am": "Con nghe và phát âm theo cô tốt. Khi không có mẫu, con còn quên âm cuối ở các từ như \"like\", \"rice\". Cô sẽ củng cố nguyên tắc IPA và chỉnh khẩu hình cho con.",
      "nx_phan_xa": "Con còn rụt rè và có tâm lý sợ sai. Càng về cuối giờ con cởi mở hơn, đã trả lời được cả câu \"I'm happy\" khi cô hỏi.",
      "diem_tu_vung": "8.4",
      "diem_ngu_phap": "8.8",
      "diem_phat_am": "9.6",
      "diem_phan_xa": "9.0",
      "pct_co_ban": "100%",
      "pct_nang_cao": "20%",
      "nhan_xet_lo_trinh": "Con phù hợp với lộ trình tăng tốc: học song song kiến thức cơ bản và mở rộng chủ đề nâng cao để chuẩn bị cho các kỳ thi trong năm học.",
      "bac_nang_luc": "Bậc 3",
      "ngay_cap": "Hà Nội, ngày 19 tháng 3 năm 2026"
    },
    {
      "ma_hoc_sinh": "HS020",
      "ho_ten": "Chu Nhật Minh",
      "giao_vien": "Trần Hoàng Mai",
      "lich_hoc": "09:00 07/03/2026",
      "lop": "D.5C.312603",
      "video_url": "https://example.com/video/buoi-hoc-20",
      "so_cup": "71",
      "gio_tay": "3",
      "tra_loi_dung": "5/10",
      "nhan_xet_tinh_than": "Con có ý thức học tập tốt, tiếp thu từ vựng và cấu trúc mới khá nhanh, tuy nhiên còn hơi rụt rè khi được gọi trả lời.",
      "hoc_luc": "C - Trung Bình",
      "nhan_xet_tong_quan": "Con nắm được kiến thức trong buổi học ở mức khá. Để tiến bộ nhanh hơn, con cần: (1) Luyện nghe chép chính tả 10 phút mỗi ngày; (2) Tăng thời lượng nói để quen phản xạ.",
      "nx_tu_vung": "Con nhớ được khoảng 4/6 từ mới. Với các từ dài, con còn nhầm lẫn thứ tự âm tiết nên cô sẽ chia nhỏ từ theo âm để con dễ ghi nhớ.",
      "nx_ngu_phap": "Con phân biệt được câu khẳng định và câu hỏi, nhưng còn quên chia động từ số ít ngôi thứ ba.",
      "nx_phat_am": "Con phát âm rõ ràng, trọng âm từ khá chuẩn. Cô sẽ nâng dần lên luyện ngữ điệu câu.",
      "nx_phan_xa": "Con phản xạ nhanh với câu hỏi quen thuộc, thời gian nghĩ trung bình dưới 3 giây.",
      "diem_tu_vung": "6.2",
      "diem_ngu_phap": "6.6",
      "diem_phat_am": "6.0",
      "diem_phan_xa": "6.8",
      "pct_co_ban": "100%",
      "pct_nang_cao": "25%",
      "nhan_xet_lo_trinh": "Trung tâm đề xuất con học nhóm nhỏ 1 kèm 3 để vừa có bạn tương tác, vừa được cô theo sát khi phát âm.",
      "bac_nang_luc": "Bậc 1-",
      "ngay_cap": "Hà Nội, ngày 20 tháng 3 năm 2026"
    }
  ],
  "levels": [
    {
      "bac": "Bậc 1-",
      "nghe": "Nghe hiểu các cụm từ quen thuộc, đơn giản. Nghe hiểu và làm theo hướng dẫn rất đơn giản trong lớp học.\nNghe hiểu và trả lời các câu hỏi rất đơn giản nếu nói chậm và rõ ràng.\nNghe hiểu đoạn hội thoại ngắn 20-30 từ về chủ đề đã học nếu nói chậm và rõ ràng.",
      "noi": "Nói các cụm từ đơn giản, quen thuộc, ngắn và dễ phát âm.\nHỏi và trả lời câu hỏi đơn giản về bản thân và người khác.\nNói được về chủ đề đã học một cách đơn giản bằng cụm từ và từ đơn.",
      "doc": "Đọc đúng chữ cái trong bảng chữ cái, chữ cái trong từ.\nĐọc hiểu nghĩa các từ và cụm từ quen thuộc, rất đơn giản.\nĐọc hiểu các văn bản ngắn 30-40 từ về chủ đề đã học.",
      "viet": "Viết các từ, cụm từ rất đơn giản.\nĐiền thông tin cá nhân vào các mẫu rất đơn giản (tên, địa chỉ...).\nViết theo mẫu để hoàn thành đoạn văn 10-20 từ."
    },
    {
      "bac": "Bậc 1",
      "nghe": "Nghe hiểu câu và cụm từ thông dụng liên quan tới bản thân, gia đình, trường lớp.\nNghe hiểu ý chính của đoạn hội thoại 40-60 từ nói với tốc độ chậm.\nNghe và làm theo chuỗi 2-3 hướng dẫn đơn giản trong lớp.",
      "noi": "Giới thiệu bản thân và người thân bằng các câu đơn hoàn chỉnh.\nĐặt và trả lời câu hỏi về nhu cầu, sở thích quen thuộc.\nMô tả ngắn về đồ vật, con vật, hoạt động hằng ngày (4-5 câu).",
      "doc": "Đọc hiểu đoạn văn 50-70 từ về chủ đề quen thuộc.\nXác định thông tin cụ thể trong bảng biểu, thời khoá biểu đơn giản.\nĐọc trôi chảy câu đơn với ngữ điệu cơ bản.",
      "viet": "Viết câu đơn hoàn chỉnh về bản thân và môi trường xung quanh.\nViết đoạn 25-40 từ theo gợi ý cho sẵn.\nSử dụng đúng dấu câu và viết hoa cơ bản."
    },
    {
      "bac": "Bậc 2",
      "nghe": "Nghe hiểu ý chính của bài nói rõ ràng về chủ đề quen thuộc trong học tập, giải trí.\nNghe hiểu hội thoại 80-100 từ và nắm được chi tiết quan trọng.\nNhận biết được thái độ, cảm xúc của người nói qua ngữ điệu.",
      "noi": "Trao đổi thông tin trong các tình huống giao tiếp quen thuộc hằng ngày.\nKể lại một sự việc, trải nghiệm bằng chuỗi câu có liên kết.\nTrình bày ý kiến cá nhân ngắn gọn kèm lý do đơn giản.",
      "doc": "Đọc hiểu văn bản 100-150 từ về chủ đề quen thuộc.\nSuy luận nghĩa của từ mới dựa vào ngữ cảnh.\nNắm được ý chính và ý chi tiết của đoạn văn ngắn.",
      "viet": "Viết đoạn văn 50-80 từ có mở - thân - kết đơn giản.\nViết tin nhắn, email ngắn cho bạn bè, thầy cô.\nSử dụng từ nối cơ bản (and, but, because, so) để liên kết ý."
    },
    {
      "bac": "Bậc 3",
      "nghe": "Nghe hiểu bài nói dài về chủ đề học thuật quen thuộc với tốc độ tự nhiên.\nNghe hiểu và ghi chép ý chính của bài giảng ngắn.\nNghe hiểu các đoạn hội thoại có nhiều người tham gia.",
      "noi": "Thảo luận, bảo vệ quan điểm cá nhân về chủ đề quen thuộc.\nThuyết trình 2-3 phút có cấu trúc rõ ràng.\nSử dụng linh hoạt cấu trúc câu phức trong giao tiếp.",
      "doc": "Đọc hiểu văn bản 200-250 từ ở nhiều thể loại khác nhau.\nPhân tích được ý đồ và quan điểm của tác giả.\nĐọc lướt lấy thông tin và đọc kỹ lấy chi tiết.",
      "viet": "Viết bài luận 120-150 từ có bố cục và lập luận rõ ràng.\nViết thư trang trọng và không trang trọng đúng văn phong.\nSử dụng đa dạng cấu trúc câu và từ vựng học thuật cơ bản."
    }
  ]
};
